version: '3.7'

services: 
  server:
    container_name: recogito-server
    build: 
      context: server
      dockerfile: Dockerfile
    expose:
      - 8080
    restart: always
    networks:
      - net
    depends_on:
      - rethinkdb
    
  rethinkdb:
    image: rethinkdb:2.4
    expose:
      - 8080
      - 28015
    volumes:
      - ./server/data:/app
    networks:
      - net

  nginx:
    depends_on: 
      - server
    container_name: proxy
    build: 
      context: ./nginx/
      dockerfile: Dockerfile
    ports: 
        - 80:80
    restart: always
    networks:
      - net
    
networks:
  net:
volumes:
  esdata:
  esplugins:
